spring:
  application:
    name: kafka-sample
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
        auto-offset-reset: earliest
        group-id: sample-group
    template:
      observation-enabled: true
    topic:
      sample: sample-topic

management:
  tracing:
    sampling:
      probability: 1